#!/bin/sh


usage() {
	echo "Usage: aim [OPTIONS] APPIMAGE"
	echo ""
	echo "Installs APPIMAGE and creates a desktop file."
	echo "  Applications are installed to '~/Applications"
	echo "  Desktop files are created at '~/.local/share/applications'"
	echo ""
	echo "Options:"
	echo "  -h    Displays this text"
	echo "  -p    Preserves the AppImage file"
	echo "  -d    Deletes the AppImage and desktop file."
}

APP_DIR="$HOME/Applications"
DESKTOP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"


while getopts ":hpd" opt; do
	case ${opt} in
		h)
			usage
			exit 0
			;;
		p)
			PRESERVE="1"
			;;
		d)
			DELETE="1"
			;;
		:)
			:
			;;
		*)
			echo "Invalid option: $opt"
			usage
			exit 1
			;;
	esac
done

shift $((OPTIND - 1))

APPIMAGE="$1"

if [ -z "$APPIMAGE" ] || [ ! -f "$APPIMAGE" ]; then
	usage
	exit 1
fi

mkdir -p "$APP_DIR" "$DESKTOP_DIR"

#Set all filepaths
FILENAME="$(basename "$APPIMAGE")"
DEST="$APP_DIR/$FILENAME"
NAME="${FILENAME%%.AppImage}"
ICON_PATH="$DESKTOP_DIR/$NAME.png"
DESKTOP_FILE="$DESKTOP_DIR/$NAME.desktop"

#Delete the AppImage, icon, and desktop files
if [ "${DELETE+x}" ]; then
	rm -f "$DEST" "$ICON_PATH" "$DESKTOP_FILE"
	echo "Removed $NAME"
	exit 0
fi

#Install the AppImage, optionally deleting the source
install "$APPIMAGE" "$DEST"
if [ -z "$PRESERVE" ]; then
	rm "$APPIMAGE"
fi

#Try to get the icon from the AppImage
"$DEST" --appimage-extract > /dev/null 2>&1
for IMG in squashfs-root/*.png; do
	if [ -f "$IMG" ]; then
		echo "Found icon: $IMG"
		cp "$IMG" "$ICON_PATH"
		ICON="$ICON_PATH"
		break
	else
		ICON=""
	fi
done
rm -rf squashfs-root

#Create the desktop file
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Name=$NAME
Exec=$DEST
Icon=$ICON
Type=Application
Categories=Utility;
Terminal=false
EOF

chmod +x "$DESKTOP_FILE"

#Complete!
echo "AppImage registered: $NAME"

